apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rubydev
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        type: dev
        version: '1.0'
        app: rubyapp
    spec:
      containers:
      - name: rubydev
        image: 10.74.50.108:5000/ruby_app:2
        ports:
        - containerPort: 8080
