apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rubydev
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        type: dev
    spec:
      containers:
      - name: rubydev
        image: 192.168.50.4:5000/ruby_app:2
        ports:
        - containerPort: 8080
